export const Images = {
    Image1:"./asets/gurudev main logo.jpg",
    // Image2:"./asets/badka_gurudev.jpg",
    Image2:"./asets/swami-ji.jpg",
    Image3:"./asets/Screenshot (27).png",
    Image4:"./asets/Screenshot (28).png",
    Image5:"./asets/book.jpg",
    Image6:"./asets/book2.jpg",
    Image7:"./asets/book3.jpg",
    Image8:"./asets/book4.jpg",
    Image9:"./asets/book5.jpg",
    Image10:"./asets/gurupurnima.jpg",
    Image11:"./asets/makhan.jpg",
    Image12:"./asjpgets/prasad.jpg",
    Image13:"./asets/gurudev ashwini.jpg",
    Image14:"./asets/guru_bhagwat.jpg",
    Image15:"./asets/bg-bhakti.jpg",
    Image16:"./asets/ramanuj.png",
    Image17:"./asets/ramanuj.png",
    Image18:"./asets/SUPER GOD IMAGES (10).jpg",
    Image19:"./asets/SUPER GOD IMAGES (12).jpg",
    Image20:"./asets/swami-bachhi.jpg",
    Image21:"./asets/swami-ji-1.jpg",
    Image22:"./asets/swami-3.jpg",
    Image23:"./asets/div_line_blue.png",
}